
const lessonData = {};

lessonData["01_Izetbegovic.mp3"] = [{
    text: "1. Alija Izetbegović. Alija Izetbegović war Anwalt und Philosoph und wurde der erste Präsident von Bosnien und Herzegowina. Er verbrachte viele Jahre im Gefängnis, weil die kommunistische Regierung seine religiösen und politischen Ideen nicht mochte. Als Jugoslawien auseinanderbrach, führte er sein Volk in Richtung Unabhängigkeit. Während des Bosnienkriegs blieb er in der Hauptstadt Sarajevo, während sie unter Beschuss stand. Er arbeitete hart, um die Einheit seines Landes zu schützen und sein Volk vor der Zerstörung zu bewahren. 1995 unterzeichnete er das Dayton-Abkommen, um die Kämpfe zu beenden. Er gilt als Vater der bosnischen Nation, weil er dem Land half, seine schwierigste Zeit zu überstehen. Er wird für seine Weisheit und seine Hingabe an Freiheit und Gerechtigkeit respektiert.",
    dict: { "anwalt":"avukat", "philosoph":"filozof", "präsident":"başkan", "gefängnis":"hapishane", "kommunistische":"komünist", "regierung":"hükümet", "religiösen":"dini", "politischen":"siyasi", "ideen":"fikirler", "auseinanderbrach":"parçalandı", "führte":"yönetti/götürdü", "unabhängigkeit":"bağımsızlık", "bosnienkriegs":"bosna savaşı", "blieb":"kaldı", "hauptstadt":"başkent", "beschuss":"ateş/bombalama", "arbeitete":"çalıştı", "einheit":"birlik", "schützen":"korumak", "bewahren":"korumak/kurtarmak", "unterzeichnete":"imzaladı", "abkommen":"anlaşma", "kämpfe":"savaşlar/çatışmalar", "beenden":"bitirmek", "vater":"baba", "nation":"ulus", "schwierigste":"en zor", "überstehen":"atlatmak", "weisheit":"bilgelik", "hingabe":"bağlılık/adanmışlık", "freiheit":"özgürlük", "gerechtigkeit":"adalet", "respektiert":"saygı duyulur" },
    questions: [ {q:"War Alija Izetbegović Anwalt und Philosoph?", a_de:"Ja", a_tr:"Evet"}, {q:"Mochte die kommunistische Regierung seine Ideen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Führte er sein Volk in Richtung Unabhängigkeit?", a_de:"Ja", a_tr:"Evet"}, {q:"Blieb er während des Krieges in Sarajevo?", a_de:"Ja", a_tr:"Evet"}, {q:"Unterzeichnete er 1995 das Dayton-Abkommen?", a_de:"Ja", a_tr:"Evet"}, {q:"Floh er aus seinem Land, um sich zu retten?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wird er für seine Weisheit und Hingabe respektiert?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["02_Cabral.mp3"] = [{
    text: "2. Amílcar Cabral. Amílcar Cabral war ein brillanter Ingenieur und revolutionärer Führer in Westafrika. Er kämpfte gegen die portugiesische Kolonialherrschaft in Guinea-Bissau und Kap Verde. Cabral glaubte, dass Freiheit nicht nur das Entfernen fremder Soldaten bedeutet, sondern auch die Verbesserung des Lebens der Armen durch Bildung und Landwirtschaft. Er organisierte einen sehr erfolgreichen Guerillakrieg, der die portugiesische Armee zum Rückzug zwang. Er war ein großer Denker, dessen Bücher über Kultur und Unabhängigkeit bis heute studiert werden. Tragischerweise wurde er von einer rivalisierenden Gruppe ermordet, nur Monate bevor sein Land frei wurde. Obwohl er die Unabhängigkeit, für die er kämpfte, nicht erlebte, wird er als einer der größten Helden Afrikas erinnert.",
    dict: { "brillanter":"parlak/zeki", "ingenieur":"mühendis", "revolutionärer":"devrimci", "führer":"lider", "kämpfte":"savaştı", "portugiesische":"portekiz", "kolonialherrschaft":"sömürge yönetimi", "glaubte":"inandı", "entfernen":"kaldırmak/çıkarmak", "fremder":"yabancı", "soldaten":"askerler", "bedeutet":"anlamına gelir", "sondern":"aksine/ayrıca", "verbesserung":"iyileştirme", "armen":"fakirler", "bildung":"eğitim", "landwirtschaft":"tarım", "organisierte":"organize etti", "erfolgreichen":"başarılı", "guerillakrieg":"gerilla savaşı", "armee":"ordu", "rückzug":"geri çekilme", "zwang":"zorladı", "denker":"düşünür", "bücher":"kitaplar", "kultur":"kültür", "studiert":"incelenir/okunur", "tragischerweise":"trajik bir şekilde", "rivalisierenden":"rakip", "ermordet":"öldürüldü (cinayet)", "monate":"aylar", "bevor":"önce", "frei":"özgür", "erlebte":"yaşadı/gördü", "größten":"en büyük", "helden":"kahramanlar", "erinnert":"hatırlanır" },
    questions: [ {q:"War Amílcar Cabral ein brillanter Ingenieur?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpfte er gegen die britische Kolonialherrschaft?", a_de:"Nein", a_tr:"Hayır"}, {q:"Glaubte er, dass Bildung und Landwirtschaft wichtig sind?", a_de:"Ja", a_tr:"Evet"}, {q:"Zwang er die portugiesische Armee zum Rückzug?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er von einer rivalisierenden Gruppe ermordet?", a_de:"Ja", a_tr:"Evet"}, {q:"Erlebte er die Unabhängigkeit seines Landes?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wird er als einer der größten Helden Afrikas erinnert?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["03_Davis.mp3"] = [{
    text: "3. Angela Davis. Angela Davis ist eine berühmte Aktivistin und Lehrerin in den Vereinigten Staaten. Sie wurde in den 1960er Jahren eine Führerin der Bürgerrechtsbewegung. Sie sprach sich lautstark gegen Rassismus und die ungerechte Behandlung von Gefangenen aus. 1970 wurde sie zu einer der bekanntesten Frauen der Welt, als sie auf die FBI-Liste der meistgesuchten Personen kam. Sie verbrachte über ein Jahr im Gefängnis für ein Verbrechen, das sie nicht begangen hatte. Nach einem langen Prozess wurde sie freigesprochen. Heute kämpft sie weiter für die Rechte aller Menschen. Sie glaubt, dass das Gefängnissystem verändert werden muss und für echte Gleichheit gearbeitet werden muss. Sie ist ein starkes Symbol des Widerstands und des Mutes für Menschen auf der ganzen Welt.",
    dict: { "berühmte":"ünlü", "aktivistin":"aktivist", "lehrerin":"öğretmen", "vereinigten":"birleşik", "staaten":"devletler", "führerin":"kadın lider", "bürgerrechtsbewegung":"sivil haklar hareketi", "sprach":"konuştu", "lautstark":"yüksek sesle", "rassismus":"ırkçılık", "ungerechte":"adaletsiz", "behandlung":"muamele", "gefangenen":"mahkumlar", "bekanntesten":"en bilinen", "frauen":"kadınlar", "welt":"dünya", "liste":"liste", "meistgesuchten":"en çok aranan", "personen":"kişiler", "verbrachte":"geçirdi", "jahr":"yıl", "gefängnis":"hapishane", "verbrechen":"suç", "begangen":"işlenmiş", "langen":"uzun", "prozess":"dava/süreç", "freigesprochen":"beraat etti", "heute":"bugün", "rechte":"haklar", "aller":"tüm", "menschen":"insanlar", "gefängnissystem":"hapishane sistemi", "verändert":"değiştirilmiş", "echte":"gerçek", "gleichheit":"eşitlik", "gearbeitet":"çalışılmış", "starkes":"güçlü", "symbol":"sembol", "widerstands":"direniş", "mutes":"cesaret" },
    questions: [ {q:"Ist Angela Davis eine berühmte Lehrerin in den USA?", a_de:"Ja", a_tr:"Evet"}, {q:"War sie eine Führerin der Bürgerrechtsbewegung?", a_de:"Ja", a_tr:"Evet"}, {q:"Sprach sie sich für Rassismus aus?", a_de:"Nein", a_tr:"Hayır"}, {q:"Kam sie auf die FBI-Liste der meistgesuchten Personen?", a_de:"Ja", a_tr:"Evet"}, {q:"Verbrachte sie zehn Jahre im Gefängnis?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde sie nach einem langen Prozess freigesprochen?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpft sie heute weiter für echte Gleichheit?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["04_Shakur.mp3"] = [{
    text: "4. Assata Shakur. Assata Shakur war Aktivistin in der Black Panther Party und kämpfte für die Rechte schwarzer Amerikaner. 1973 war sie in eine Schießerei auf einer Autobahn verwickelt, bei der ein Polizist getötet wurde. Sie wurde verletzt und von der Polizei gefasst. Obwohl sie ihre Unschuld beteuerte, wurde sie zu lebenslanger Haft verurteilt. 1979 gelang ihr mit Hilfe ihrer Freunde die Flucht aus dem Gefängnis. Sie reiste heimlich nach Kuba, wo die Regierung ihr Schutz gewährte. Sie lebt bis heute in Kuba. Viele Aktivisten sehen sie als Heldin, die ein sehr ungerechtes System überlebte, während die US-Regierung sie weiterhin verhaften will. Ihre Geschichte ist ein berühmtes Beispiel für den Kampf um Bürgerrechte.",
    dict: { "black":"siyah", "panther":"panter", "party":"parti", "amerikaner":"amerikalılar", "schießerei":"silahlı çatışma", "autobahn":"otoyol", "verwickelt":"karışmış", "polizist":"polis memuru", "getötet":"öldürüldü", "verletzt":"yaralı", "gefasst":"yakalandı", "unschuld":"masumiyet", "beteuerte":"iddia etti/savundu", "lebenslanger":"ömür boyu", "haft":"hapis", "verurteilt":"mahkum edildi", "gelang":"başardı", "hilfe":"yardım", "flucht":"kaçış", "reiste":"seyahat etti", "heimlich":"gizlice", "kuba":"küba", "schutz":"koruma", "gewährte":"sağladı/verdi", "lebt":"yaşıyor", "heldin":"kadın kahraman", "ungerechtes":"adaletsiz", "system":"sistem", "überlebte":"hayatta kaldı", "weiterhin":"hala/devam ederek", "verhaften":"tutuklamak" },
    questions: [ {q:"War Assata Shakur in der Black Panther Party?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde bei der Schießerei ein Polizist getötet?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde sie zu nur zwei Jahren Gefängnis verurteilt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Gelang ihr 1979 die Flucht aus dem Gefängnis?", a_de:"Ja", a_tr:"Evet"}, {q:"Reiste sie heimlich nach Frankreich?", a_de:"Nein", a_tr:"Hayır"}, {q:"Gewährte die Regierung von Kuba ihr Schutz?", a_de:"Ja", a_tr:"Evet"}, {q:"Will die US-Regierung sie weiterhin verhaften?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["05_Singh.mp3"] = [{
    text: "5. Bhagat Singh. Bhagat Singh war ein junger und mutiger Revolutionär in Indien. Er kämpfte gegen die britische Herrschaft, weil er wollte, dass sein Land frei und gerecht für alle wird. Er stimmte nicht nur mit gewaltlosen Protesten überein; er glaubte, dass starke Aktionen nötig seien, um die Menschen aufzuwecken. 1929 warf er eine kleine Bombe in ein Regierungsgebäude, um gegen ungerechte Gesetze zu protestieren. Er wollte niemanden verletzen, sondern die Briten zum Zuhören zwingen. Er wurde verhaftet und blieb im Gefängnis sehr stark. Die Briten richteten ihn mit nur 23 Jahren hin. Sein Opfer machte ihn zur Legende in Indien und Pakistan. Heute schauen junge Menschen noch immer zu ihm als Symbol für Mut und Patriotismus auf.",
    dict: { "junger":"genç", "mutiger":"cesur", "revolutionär":"devrimci", "indien":"hindistan", "britische":"ingiliz", "herrschaft":"yönetim", "gerecht":"adil", "stimmte":"katıldı (übereinstimmen)", "gewaltlosen":"şiddetsiz", "protesten":"protestolar", "überein":"aynı fikirde", "starke":"güçlü", "aktionen":"eylemler", "nötig":"gerekli", "seien":"oldukları", "aufzuwecken":"uyandırmak", "warf":"fırlattı", "kleine":"küçük", "bombe":"bomba", "regierungsgebäude":"hükümet binası", "gesetze":"yasalar", "niemanden":"hiç kimseyi", "verletzen":"yaralamak", "zuhören":"dinlemek", "zwingen":"zorlamak", "verhaftet":"tutuklandı", "blieb":"kaldı", "stark":"güçlü", "richteten":"infaz ettiler (hinrichten)", "jahren":"yaş", "hin":"(hinrichten)", "opfer":"fedakarlık", "legende":"efsane", "pakistan":"pakistan", "schauen":"bakarlar", "mut":"cesaret", "patriotismus":"vatanseverlik" },
    questions: [ {q:"War Bhagat Singh ein Revolutionär in Indien?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpfte er gegen die französische Herrschaft?", a_de:"Nein", a_tr:"Hayır"}, {q:"Warf er 1929 eine Bombe in ein Regierungsgebäude?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte er mit der Bombe viele Menschen verletzen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Blieb er im Gefängnis sehr stark?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er mit nur 23 Jahren hingerichtet?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist er heute eine Legende in Indien und Pakistan?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["06_Sands.mp3"] = [{
    text: "6. Bobby Sands. Bobby Sands war Mitglied der IRA in Nordirland. Er wollte, dass sein Land unabhängig von der britischen Herrschaft wird. Während er im Gefängnis war, leitete er 1981 einen berühmten Hungerstreik. Er und andere Gefangene verweigerten das Essen, weil sie als politische Gefangene behandelt werden wollten, nicht als Kriminelle. Während des Streiks wurde er sogar ins britische Parlament gewählt. Nach 66 Tagen ohne Nahrung starb Bobby Sands. Sein Tod löste weltweit massive Reaktionen aus und lenkte viel Aufmerksamkeit auf die Probleme in Nordirland. Er wird als Mann erinnert, der bereit war, sein Leben für seine politischen Überzeugungen und die Freiheit seines Landes zu geben.",
    dict: { "mitglied":"üye", "nordirland":"kuzey irlanda", "unabhängig":"bağımsız", "leitete":"yönetti", "berühmten":"ünlü", "hungerstreik":"açlık grevi", "gefangene":"mahkumlar", "verweigerten":"reddettiler", "essen":"yemek", "politische":"siyasi", "behandelt":"muamele görmek", "kriminelle":"suçlular", "streiks":"grev", "sogar":"hatta", "parlament":"parlamento", "gewählt":"seçildi", "tagen":"günler", "nahrung":"gıda/yiyecek", "starb":"öldü", "tod":"ölüm", "löste":"tetikledi (auslösen)", "weltweit":"dünya çapında", "massive":"devasa", "reaktionen":"tepkiler", "aus":"(auslösen)", "lenkte":"yönlendirdi", "aufmerksamkeit":"dikkat", "probleme":"sorunlar", "erinnert":"hatırlanır", "bereit":"hazır", "überzeugungen":"inançlar", "geben":"vermek" },
    questions: [ {q:"War Bobby Sands ein Mitglied der IRA?", a_de:"Ja", a_tr:"Evet"}, {q:"Leitete er 1981 einen Hungerstreik?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollten die Gefangenen als Kriminelle behandelt werden?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er während des Streiks ins britische Parlament gewählt?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb Bobby Sands nach 66 Tagen ohne Nahrung?", a_de:"Ja", a_tr:"Evet"}, {q:"Interessierte sich niemand auf der Welt für seinen Tod?", a_de:"Nein", a_tr:"Hayır"}, {q:"War er bereit, sein Leben für die Freiheit zu geben?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["07_Guevara.mp3"] = [{
    text: "7. Che Guevara. Ernesto „Che“ Guevara war ein Arzt aus Argentinien, der zum globalen Symbol der Revolution wurde. Auf seinen Reisen als junger Mann sah er die schreckliche Armut in Lateinamerika und beschloss, für die Armen zu kämpfen. Er schloss sich Fidel Castro an und half, die Kubanische Revolution 1959 zum Sieg zu führen. Nach dem Krieg hatte er wichtige Posten in der neuen Regierung, wollte aber auch anderen Ländern helfen. Er reiste nach Afrika und dann nach Bolivien, um neue Revolutionen zu starten. 1967 wurde er in den Bergen Boliviens gefasst und getötet. Heute ist sein Gesicht weltberühmt. Die Menschen sehen ihn als Symbol des Aufstands gegen ungerechte Macht.",
    dict: { "arzt":"doktor", "argentinien":"arjantin", "globalen":"küresel", "reisen":"seyahatler", "sah":"gördü", "schreckliche":"korkunç", "armut":"yoksulluk", "lateinamerika":"latin amerika", "beschloss":"karar verdi", "armen":"fakirler", "schloss":"katıldı (sich anschließen)", "half":"yardım etti", "kubanische":"küba", "sieg":"zafer", "krieg":"savaş", "wichtige":"önemli", "posten":"görevler/pozisyonlar", "neuen":"yeni", "ländern":"ülkeler", "afrika":"afrika", "bolivien":"bolivya", "starten":"başlatmak", "bergen":"dağlar", "gefasst":"yakalandı", "gesicht":"yüz", "weltberühmt":"dünya çapında ünlü", "aufstands":"isyan", "ungerechte":"adaletsiz", "macht":"güç" },
    questions: [ {q:"War Che Guevara ein Arzt aus Argentinien?", a_de:"Ja", a_tr:"Evet"}, {q:"Sah er als junger Mann viel Reichtum auf seinen Reisen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Half er Fidel Castro bei der Kubanischen Revolution?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er nach dem Krieg wichtige Posten in der Regierung?", a_de:"Ja", a_tr:"Evet"}, {q:"Reiste er nach Afrika und Bolivien?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er in Bolivien gefasst und getötet?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist sein Gesicht heute in der ganzen Welt unbekannt?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["08_Gezmis.mp3"] = [{
    text: "8. Deniz Gezmiş. Deniz Gezmiş war Studentenführer und Revolutionär in der Türkei. Ende der 1960er Jahre leitete er viele Proteste gegen fremden Einfluss und für die Rechte von Arbeitern und Studenten. Er glaubte, die Türkei sollte ein völlig unabhängiges und sozialistisches Land sein. Er gründete eine Gruppe, die bewaffnete Aktionen gegen die Regierung einsetzte. Nach einem Militärputsch 1971 wurde er gefasst und vor Gericht gestellt. Er blieb sehr mutig und entschuldigte sich nie für seine Taten. 1972 wurde er mit 25 Jahren gehängt. Sein Tod machte ihn für viele junge Menschen in der Türkei zum Helden. Bis heute wird er als Symbol für den Kampf um eine bessere und gerechtere Welt erinnert.",
    dict: { "studentenführer":"öğrenci lideri", "türkei":"türkiye", "ende":"son", "leitete":"yönetti", "proteste":"protestolar", "fremden":"yabancı", "einfluss":"etki", "rechte":"haklar", "arbeitern":"işçiler", "studenten":"öğrenciler", "sollte":"olmalı", "völlig":"tamamen", "sozialistisches":"sosyalist", "gründete":"kurdu", "bewaffnete":"silahlı", "aktionen":"eylemler", "einsetzte":"kullandı", "militärputsch":"askeri darbe", "vor":"önüne", "gericht":"mahkeme", "gestellt":"çıkarıldı", "mutig":"cesur", "entschuldigte":"özür diledi", "nie":"asla", "taten":"eylemler", "gehängt":"asıldı", "tod":"ölüm", "helden":"kahraman", "bessere":"daha iyi", "gerechtere":"daha adil" },
    questions: [ {q:"War Deniz Gezmiş ein Studentenführer in der Türkei?", a_de:"Ja", a_tr:"Evet"}, {q:"Leitete er Proteste für die Rechte von Arbeitern?", a_de:"Ja", a_tr:"Evet"}, {q:"Gründete er eine Gruppe für bewaffnete Aktionen?", a_de:"Ja", a_tr:"Evet"}, {q:"Entschuldigte er sich vor Gericht für seine Taten?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er nach einem Militärputsch gefasst?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er mit 25 Jahren gehängt?", a_de:"Ja", a_tr:"Evet"}, {q:"Wird er heute von jungen Menschen vergessen?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["09_Bouhired.mp3"] = [{
    text: "9. Djamila Bouhired. Djamila Bouhired ist eine der berühmtesten Frauen in der Geschichte Nordafrikas. Sie war Widerstandskämpferin im Kampf Algeriens um Unabhängigkeit von Frankreich. Während des Krieges führte sie gefährliche Missionen in der Stadt Algier durch. Sie wurde schließlich gefasst und von französischen Soldaten gefoltert, gab aber nie die Geheimnisse ihrer Gruppe preis. Sie wurde zum Tode verurteilt, doch Menschen auf der ganzen Welt protestierten, um ihr Leben zu retten. Wegen dieses internationalen Drucks wurde sie freigelassen, als Algerien 1962 frei wurde. Sie ist eine Nationalheldin und ein Symbol dafür, wie wichtig Frauen im Kampf um Freiheit und nationale Würde waren.",
    dict: { "berühmtesten":"en ünlü", "geschichte":"tarih", "nordafrikas":"kuzey afrika", "widerstandskämpferin":"direniş savaşçısı", "kampf":"mücadele", "algeriens":"cezayir'in", "unabhängigkeit":"bağımsızlık", "frankreich":"fransa", "führte":"yürüttü", "gefährliche":"tehlikeli", "missionen":"görevler", "stadt":"şehir", "algier":"cezayir (şehir)", "durch":"(durchführen)", "schließlich":"sonunda", "französischen":"fransız", "soldaten":"askerler", "gefoltert":"işkence gördü", "gab":"verdi (preisgeben)", "geheimnisse":"sırlar", "preis":"(preisgeben)", "tode":"ölüm", "verurteilt":"mahkum edildi", "menschen":"insanlar", "ganzen":"tüm", "protestierten":"protesto ettiler", "retten":"kurtarmak", "internationalen":"uluslararası", "drucks":"baskı", "freigelassen":"serbest bırakıldı", "frei":"özgür", "nationalheldin":"ulusal kahraman", "würde":"onur/haysiyet" },
    questions: [ {q:"Ist Djamila Bouhired eine berühmte Frau in Nordafrika?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpfte sie für die Unabhängigkeit Algeriens?", a_de:"Ja", a_tr:"Evet"}, {q:"Verriet sie die Geheimnisse ihrer Gruppe unter Folter?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde sie zum Tode verurteilt?", a_de:"Ja", a_tr:"Evet"}, {q:"Protestierten Menschen weltweit, um ihr Leben zu retten?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde sie am Ende von den Soldaten hingerichtet?", a_de:"Nein", a_tr:"Hayır"}, {q:"Ist sie ein Symbol für die Wichtigkeit von Frauen im Freiheitskampf?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["10_Fanon.mp3"] = [{
    text: "10. Frantz Fanon. Frantz Fanon war Arzt und sehr wichtiger Schriftsteller aus Martinique. Er untersuchte, wie Kolonialismus und Rassismus die Psyche der Menschen verletzen. Er zog nach Algerien und schloss sich dem Kampf um Unabhängigkeit gegen Frankreich an. Er schrieb mehrere berühmte Bücher, wie „Die Verdammten dieser Erde“, die erklärten, warum unterdrückte Völker das Recht haben, für ihre Freiheit zu kämpfen. Er glaubte, dass kolonisierte Menschen stolz auf ihre eigene Kultur sein müssen, um wirklich frei zu sein. Seine Ideen inspirierten viele Freiheitsbewegungen in Afrika, der Karibik und Amerika. Obwohl er sehr jung an einer Krankheit starb, werden seine Bücher bis heute von Millionen gelesen, die Gerechtigkeit und Gleichheit verstehen wollen.",
    dict: { "wichtiger":"önemli", "schriftsteller":"yazar", "martinique":"martinik", "untersuchte":"inceledi", "kolonialismus":"sömürgecilik", "rassismus":"ırkçılık", "psyche":"psikoloji/ruh hali", "verletzen":"yaralamak/zarar vermek", "zog":"taşındı", "schloss":"katıldı", "schrieb":"yazdı", "mehrere":"birçok", "bücher":"kitaplar", "verdammten":"lanetliler", "erde":"dünya/yeryüzü", "erklärten":"açıkladılar", "warum":"neden", "unterdrückte":"ezilen", "völker":"halklar", "recht":"hak", "stolz":"gururlu", "eigene":"kendi", "kultur":"kültür", "müssen":"zorundalar", "wirklich":"gerçekten", "ideen":"fikirler", "inspirierten":"ilham verdi", "freiheitsbewegungen":"özgürlük hareketleri", "karibik":"karayipler", "amerika":"amerika", "krankheit":"hastalık", "gelesen":"okunur", "verstehen":"anlamak" },
    questions: [ {q:"War Frantz Fanon ein Arzt und Schriftsteller?", a_de:"Ja", a_tr:"Evet"}, {q:"Untersuchte er, wie Rassismus die Psyche der Menschen verletzt?", a_de:"Ja", a_tr:"Evet"}, {q:"Zog er nach Kanada, um dort zu leben?", a_de:"Nein", a_tr:"Hayır"}, {q:"Schrieb er das berühmte Buch „Die Verdammten dieser Erde“?", a_de:"Ja", a_tr:"Evet"}, {q:"Glaubte er, dass kolonisierte Menschen stolz auf ihre Kultur sein müssen?", a_de:"Ja", a_tr:"Evet"}, {q:"Inspirierten seine Ideen viele Freiheitsbewegungen?", a_de:"Ja", a_tr:"Evet"}, {q:"Werden seine Bücher heute nicht mehr gelesen?", a_de:"Nein", a_tr:"Hayır"} ]
}];lessonData["11_Hampton.mp3"] = [{
    text: "11. Fred Hampton. Fred Hampton war ein brillanter junger Führer der Black Panther Party in Chicago. Er war ein sehr begabter Redner, der Menschen aller Rassen vereinen wollte, um gegen Armut und Rassismus zu kämpfen. Er gründete die „Rainbow Coalition“, um Schwarze, Hispanics und weiße Arbeiterklasse zusammenzubringen. Er startete Programme, um armen Kindern kostenlos Frühstück zu geben. Regierung und Polizei hatten große Angst vor seiner Fähigkeit, Menschen zu vereinen. 1969 stürmten Polizei und FBI seine Wohnung, während er schlief, und töteten ihn. Er war nur 21 Jahre alt. Sein Tod gilt als tragische Ermordung eines Mannes, der Frieden und Einheit für alle wollte.",
    dict: { "brillanter":"parlak", "führer":"lider", "begabter":"yetenekli", "redner":"konuşmacı", "rassen":"ırklar", "vereinen":"birleştirmek", "armut":"yoksulluk", "rassismus":"ırkçılık", "kämpfen":"savaşmak", "gründete":"kurdu", "weiße":"beyaz", "arbeiterklasse":"işçi sınıfı", "zusammenzubringen":"bir araya getirmek", "startete":"başlattı", "programme":"programlar", "armen":"fakir", "kindern":"çocuklar", "kostenlos":"ücretsiz", "frühstück":"kahvaltı", "geben":"vermek", "regierung":"hükümet", "polizei":"polis", "angst":"korku", "fähigkeit":"yetenek", "stürmten":"bastılar", "wohnung":"daire/ev", "schlief":"uyuyordu", "töteten":"öldürdüler", "tod":"ölüm", "gilt":"kabul edilir", "tragische":"trajik", "ermordung":"cinayet", "frieden":"barış", "einheit":"birlik" },
    questions: [ {q:"War Fred Hampton ein Führer der Black Panther Party?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte er Menschen aller Rassen vereinen?", a_de:"Ja", a_tr:"Evet"}, {q:"Gab er armen Kindern kostenloses Frühstück?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatten die Regierung und die Polizei keine Angst vor ihm?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er im Schlaf von der Polizei und dem FBI getötet?", a_de:"Ja", a_tr:"Evet"}, {q:"War er bei seinem Tod 40 Jahre alt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wollte er Frieden und Einheit für alle?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["12_HoChiMinh.mp3"] = [{
    text: "12. Ho Chi Minh. Ho Chi Minh war der wichtigste Führer in der Geschichte Vietnams. Er reiste jahrelang um die Welt, um einen Weg zu finden, sein Land von der französischen Herrschaft zu befreien. Er gründete die Kommunistische Partei Vietnams und leitete den Widerstand jahrzehntelang. Nach dem Rückzug der Franzosen führte er Nordvietnam im Krieg gegen die USA. Er war ein sehr einfacher Mann, der ein ruhiges Leben führte, doch sein Volk liebte ihn und nannte ihn „Onkel Ho“. Er starb vor Kriegsende, doch sein Traum von einem vereinten und unabhängigen Vietnam wurde 1975 wahr. Die größte Stadt des Landes wurde in Ho-Chi-Minh-Stadt umbenannt, um sein Andenken zu ehren.",
    dict: { "wichtigste":"en önemli", "geschichte":"tarih", "vietnams":"vietnam'ın", "reiste":"seyahat etti", "jahrelang":"yıllarca", "welt":"dünya", "weg":"yol", "finden":"bulmak", "französischen":"fransız", "herrschaft":"yönetim", "befreien":"kurtarmak", "gründete":"kurdu", "kommunistische":"komünist", "partei":"parti", "leitete":"yönetti", "widerstand":"direniş", "jahrzehntelang":"onyıllarca", "rückzug":"geri çekilme", "franzosen":"fransızlar", "führte":"yönetti", "nordvietnam":"kuzey vietnam", "krieg":"savaş", "usa":"abd", "einfacher":"basit/sade", "ruhiges":"sakin", "leben":"hayat", "volk":"halk", "liebte":"sevdi", "nannte":"adlandırdı", "onkel":"amca", "starb":"öldü", "kriegsende":"savaşın sonu", "traum":"rüya/hayal", "vereinten":"birleşik", "unabhängigen":"bağımsız", "wahr":"gerçek (wahr werden: gerçekleşmek)", "größte":"en büyük", "stadt":"şehir", "umbenannt":"yeniden adlandırıldı", "andenken":"anı/hatıra", "ehren":"onurlandırmak" },
    questions: [ {q:"War Ho Chi Minh der wichtigste Führer Vietnams?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte er sein Land von den Briten befreien?", a_de:"Nein", a_tr:"Hayır"}, {q:"Führte er Nordvietnam im Krieg gegen die USA?", a_de:"Ja", a_tr:"Evet"}, {q:"War er ein Mann, der ein sehr reiches und luxuriöses Leben führte?", a_de:"Nein", a_tr:"Hayır"}, {q:"Nannte sein Volk ihn „Onkel Ho“?", a_de:"Ja", a_tr:"Evet"}, {q:"Erlebte er das Ende des Krieges?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde die größte Stadt Vietnams nach ihm benannt?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["13_MalcolmX.mp3"] = [{
    text: "13. Malcolm X. Malcolm X war ein mächtiger Führer, der für die Rechte afroamerikanischer Menschen kämpfte. Er glaubte, dass Schwarze stolz auf ihre Identität sein und sich gegen ungerechte Behandlung verteidigen sollten. Er war ein sehr berühmter Redner, der die Wahrheit über Rassismus in Amerika sagte. Später in seinem Leben unternahm er eine religiöse Reise nach Mekka. Diese Erfahrung veränderte seine Sicht auf viele Dinge, und er begann zu glauben, dass Menschen aller Rassen für Menschenrechte zusammenarbeiten können. Er war ein Mann von großem Mut, der nie Angst hatte, seine Meinung zu sagen. 1965 wurde er getötet, doch seine Ideen über Gerechtigkeit und Selbstachtung inspirieren bis heute Millionen Menschen weltweit.",
    dict: { "mächtiger":"güçlü", "führer":"lider", "rechte":"haklar", "afroamerikanischer":"afrikalı-amerikalı", "menschen":"insanlar", "kämpfte":"savaştı", "glaubte":"inandı", "stolz":"gururlu", "identität":"kimlik", "ungerechte":"adaletsiz", "behandlung":"muamele", "verteidigen":"savunmak", "sollten":"gerektiğini", "berühmter":"ünlü", "redner":"konuşmacı", "wahrheit":"gerçek", "rassismus":"ırkçılık", "amerika":"amerika", "sagte":"söyledi", "später":"sonra", "leben":"hayat", "unternahm":"yaptı/girişti", "religiöse":"dini", "reise":"seyahat", "mekka":"mekke", "erfahrung":"deneyim", "veränderte":"değiştirdi", "sicht":"bakış açısı", "dinge":"şeyler", "begann":"başladı", "rassen":"ırklar", "menschenrechte":"insan hakları", "zusammenarbeiten":"birlikte çalışmak", "können":"yapabilmek", "großem":"büyük", "mut":"cesaret", "nie":"asla", "angst":"korku", "meinung":"fikir", "getötet":"öldürüldü", "ideen":"fikirler", "gerechtigkeit":"adalet", "selbstachtung":"özsaygı", "inspirieren":"ilham verir", "millionen":"milyonlar", "weltweit":"dünya çapında" },
    questions: [ {q:"Kämpfte Malcolm X für die Rechte afroamerikanischer Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Glaubte er, dass Schwarze stolz auf ihre Identität sein sollten?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er Angst, die Wahrheit über Rassismus zu sagen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Veränderte die Reise nach Mekka seine Sicht auf viele Dinge?", a_de:"Ja", a_tr:"Evet"}, {q:"Glaubte er später, dass alle Rassen zusammenarbeiten können?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er im Jahr 1965 getötet?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurden seine Ideen nach seinem Tod vergessen?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["14_Mandela.mp3"] = [{
    text: "14. Nelson Mandela. Nelson Mandela gehört zu den am meisten respektierten Menschen der Geschichte. Er verbrachte sein Leben im Kampf gegen die „Apartheid“, ein grausames rassistisches System in Südafrika. Er war Anwalt und wurde Führer des Widerstands. Wegen seiner Arbeit sperrte die Regierung ihn 27 Jahre lang ein. Selbst in seiner kleinen Zelle gab er die Hoffnung auf ein freies Land nie auf. 1990 wurde er endlich freigelassen und arbeitete mit seinen ehemaligen Feinden zusammen, um eine neue Demokratie zu schaffen. 1994 wurde er der erste schwarze Präsident Südafrikas. Er wählte Vergebung gegenüber denen, die ihm wehgetan hatten, und zeigte der Welt die Kraft von Frieden und Versöhnung.",
    dict: { "gehört":"aittir (zu den... gehören: ...arasında yer almak)", "meisten":"en çok", "respektierten":"saygı duyulan", "geschichte":"tarih", "verbrachte":"geçirdi", "kampf":"mücadele", "grausames":"zalim", "rassistisches":"ırkçı", "system":"sistem", "südafrika":"güney afrika", "anwalt":"avukat", "führer":"lider", "widerstands":"direniş", "wegen":"yüzünden", "arbeit":"iş/çalışma", "sperrte":"kilitledi (einsperren: hapsetmek)", "jahre":"yıllar", "lang":"boyunca", "selbst":"bile (selbst in: ...içinde bile)", "kleinen":"küçük", "zelle":"hücre", "gab":"verdi (aufgeben: vazgeçmek/pes etmek)", "hoffnung":"umut", "freies":"özgür", "nie":"asla", "auf":"(aufgeben)", "endlich":"sonunda", "freigelassen":"serbest bırakıldı", "arbeitete":"çalıştı", "ehemaligen":"eski", "feinden":"düşmanlar", "zusammen":"birlikte", "neue":"yeni", "demokratie":"demokrasi", "schaffen":"yaratmak", "erste":"ilk", "schwarze":"siyah", "präsident":"başkan", "wählte":"seçti", "vergebung":"affetme", "gegenüber":"karşı", "denen":"onlara", "wehgetan":"incitmiş (wehtun: can yakmak)", "zeigte":"gösterdi", "welt":"dünya", "kraft":"güç", "frieden":"barış", "versöhnung":"uzlaşma" },
    questions: [ {q:"Kämpfte Nelson Mandela gegen die Apartheid?", a_de:"Ja", a_tr:"Evet"}, {q:"War die Apartheid ein faires System?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verbrachte Mandela 27 Jahre im Gefängnis?", a_de:"Ja", a_tr:"Evet"}, {q:"Gab er in seiner Zelle die Hoffnung auf?", a_de:"Nein", a_tr:"Hayır"}, {q:"Arbeitete er nach seiner Freilassung mit seinen ehemaligen Feinden zusammen?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er 1994 der erste schwarze Präsident Südafrikas?", a_de:"Ja", a_tr:"Evet"}, {q:"Wählte er Rache statt Vergebung?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["15_Mukhtar.mp3"] = [{
    text: "15. Omar Mukhtar. Omar Mukhtar war ein religiöser Lehrer, der zum legendären Krieger in Libyen wurde. Als Italien sein Land überfiel, organisierte er eine Gruppe von Kämpfern, um das Land zu verteidigen. Er war Experte für „Guerillakrieg“ – schnelle Angriffe und dann Verstecken in der Wüste. 20 Jahre lang kämpfte er gegen die mächtige italienische Armee, obwohl seine Gruppe viel kleiner war. Er war ein Mann von großer Ehre und Glauben. 1931 wurde er gefasst und von den Italienern hingerichtet. Vor seinem Tod sagte er berühmt, dass sein Volk niemals kapitulieren werde. Er ist als „Löwe der Wüste“ bekannt und ein Held für alle Libyer und Araber.",
    dict: { "religiöser":"dini", "lehrer":"öğretmen", "legendären":"efsanevi", "krieger":"savaşçı", "libyen":"libya", "italien":"italya", "land":"ülke", "überfiel":"işgal etti", "organisierte":"organize etti", "gruppe":"grup", "kämpfern":"savaşçılar", "verteidigen":"savunmak", "experte":"uzman", "guerillakrieg":"gerilla savaşı", "schnelle":"hızlı", "angriffe":"saldırılar", "verstecken":"saklanmak", "wüste":"çöl", "jahre":"yıllar", "kämpfte":"savaştı", "gegen":"karşı", "mächtige":"güçlü", "italienische":"italyan", "armee":"ordu", "obwohl":"rağmen", "kleiner":"daha küçük", "mann":"adam", "großer":"büyük", "ehre":"onur", "glauben":"inanç", "gefasst":"yakalandı", "italienern":"italyanlar", "hingerichtet":"idam edildi", "tod":"ölüm", "sagte":"söyledi", "berühmt":"ünlü bir şekilde", "volk":"halk", "niemals":"asla", "kapitulieren":"teslim olmak", "bekannt":"bilinir", "held":"kahraman", "libyer":"libyalılar", "araber":"araplar" },
    questions: [ {q:"War Omar Mukhtar ein Lehrer, der zum Krieger wurde?", a_de:"Ja", a_tr:"Evet"}, {q:"Überfiel Frankreich sein Land?", a_de:"Nein", a_tr:"Hayır"}, {q:"War er Experte für schnelle Angriffe in der Wüste?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpfte er 20 Jahre lang gegen die italienische Armee?", a_de:"Ja", a_tr:"Evet"}, {q:"War seine Gruppe größer als die italienische Armee?", a_de:"Nein", a_tr:"Hayır"}, {q:"Sagte er vor seinem Tod, dass sein Volk kapitulieren werde?", a_de:"Nein", a_tr:"Hayır"}, {q:"Ist er als der „Löwe der Wüste“ bekannt?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["16_Lumumba.mp3"] = [{
    text: "16. Patrice Lumumba. Patrice Lumumba war der erste Premierminister der unabhängigen Republik Kongo. Er war ein leidenschaftlicher Führer, der wollte, dass sein Land wirklich frei von belgischer Kontrolle wird. Er glaubte, dass Afrikas Reichtum den afrikanischen Menschen gehören sollte. Nach seiner Wahl stand er vielen Problemen durch ausländische Länder und Rebellen im eigenen Land gegenüber. Weil er sehr unabhängig und stark war, wurden mächtige Länder seine Feinde. Er wurde in einem Putsch abgesetzt und 1961 getötet. Er war nur 35 Jahre alt. Heute gilt er als Symbol des Kampfes um afrikanische Unabhängigkeit und als Märtyrer für den Traum von einem vereinten und starken Afrika.",
    dict: { "erste":"ilk", "premierminister":"başbakan", "unabhängigen":"bağımsız", "republik":"cumhuriyet", "kongo":"kongo", "leidenschaftlicher":"tutkulu", "führer":"lider", "wirklich":"gerçekten", "frei":"özgür", "belgischer":"belçika", "kontrolle":"kontrol", "glaubte":"inandı", "afrikas":"afrika'nın", "reichtum":"zenginlik", "afrikanischen":"afrikalı", "menschen":"insanlar", "gehören":"ait olmak", "sollte":"gerektiğini", "wahl":"seçim", "stand":"durdu (gegenüberstehen: karşı karşıya kalmak)", "problemen":"sorunlar", "ausländische":"yabancı", "länder":"ülkeler", "rebellen":"isyancılar", "eigenen":"kendi", "gegenüber":"karşı/yüz yüze", "unabhängig":"bağımsız", "stark":"güçlü", "mächtige":"güçlü", "feinde":"düşmanlar", "putsch":"darbe", "abgesetzt":"görevden alındı", "getötet":"öldürüldü", "jahre":"yaş", "heute":"bugün", "gilt":"kabul edilir", "symbol":"sembol", "kampf":"mücadele", "märtyrer":"şehit", "traum":"rüya/hayal", "vereinten":"birleşik", "starken":"güçlü" },
    questions: [ {q:"War Patrice Lumumba der erste Premierminister der Republik Kongo?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte er, dass Belgien sein Land weiter kontrolliert?", a_de:"Nein", a_tr:"Hayır"}, {q:"Glaubte er, Afrikas Reichtum sollte den Afrikanern gehören?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er nach seiner Wahl viele Probleme mit ausländischen Ländern?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurden mächtige Länder seine Freunde?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er in einem Putsch abgesetzt und getötet?", a_de:"Ja", a_tr:"Evet"}, {q:"Gilt er heute als Märtyrer für ein vereintes Afrika?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["17_Parks.mp3"] = [{
    text: "17. Rosa Parks. Rosa Parks ist als „Mutter der Bürgerrechtsbewegung“ bekannt. 1955 weigerte sie sich in Alabama, ihren Sitzplatz im Bus einem weißen Mann zu überlassen, obwohl das Gesetz es verlangte. Ihre Verhaftung löste einen massiven Protest aus, bei dem schwarze Menschen über ein Jahr lang die Busse boykottierten. Dieser Protest wurde von Martin Luther King Jr. geleitet und zwang die Regierung schließlich, die ungerechten Gesetze zu ändern. Rosa Parks zeigte der Welt, dass eine Person eine große Veränderung auslösen kann, indem sie einfach „Nein“ zu Ungerechtigkeit sagt. Den Rest ihres Lebens arbeitete sie für Frieden und Gleichheit für alle Menschen.",
    dict: { "mutter":"anne", "bürgerrechtsbewegung":"sivil haklar hareketi", "bekannt":"bilinir", "weigerte":"reddetti", "sitzplatz":"koltuk/oturma yeri", "bus":"otobüs", "weißen":"beyaz", "mann":"adam", "überlassen":"bırakmak/devretmek", "obwohl":"rağmen", "gesetz":"yasa", "verlangte":"istedi/talep etti", "verhaftung":"tutuklama", "löste":"tetikledi (auslösen)", "massiven":"büyük/devasa", "protest":"protesto", "aus":"(auslösen)", "schwarze":"siyah", "menschen":"insanlar", "jahr":"yıl", "lang":"boyunca", "busse":"otobüsler", "boykottierten":"boykot ettiler", "geleitet":"yönetildi", "zwang":"zorladı", "regierung":"hükümet", "schließlich":"sonunda", "ungerechten":"adaletsiz", "gesetze":"yasalar", "ändern":"değiştirmek", "zeigte":"gösterdi", "welt":"dünya", "person":"kişi", "große":"büyük", "veränderung":"değişim", "auslösen":"tetiklemek/başlatmak", "kann":"yapabilir", "indem":"yaparak/ederek", "einfach":"basitçe", "nein":"hayır", "ungerechtigkeit":"adaletsizlik", "sagt":"söyler", "rest":"geri kalan", "lebens":"hayat", "arbeitete":"çalıştı", "frieden":"barış", "gleichheit":"eşitlik" },
    questions: [ {q:"Ist Rosa Parks als Mutter der Bürgerrechtsbewegung bekannt?", a_de:"Ja", a_tr:"Evet"}, {q:"Überließ sie 1955 ihren Sitzplatz einem weißen Mann?", a_de:"Nein", a_tr:"Hayır"}, {q:"Löste ihre Verhaftung einen massiven Protest aus?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde der Protest von Martin Luther King Jr. geleitet?", a_de:"Ja", a_tr:"Evet"}, {q:"Zwang der Protest die Regierung, die Gesetze zu ändern?", a_de:"Ja", a_tr:"Evet"}, {q:"Zeigte sie, dass eine Person keine Veränderung auslösen kann?", a_de:"Nein", a_tr:"Hayır"}, {q:"Arbeitete sie den Rest ihres Lebens für Frieden und Gleichheit?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["18_Machel.mp3"] = [{
    text: "18. Samora Machel. Samora Machel war der Führer, der Mosambik die Unabhängigkeit brachte. Er leitete jahrelang einen langen und schwierigen Krieg gegen die portugiesische Armee. Er war ein charismatischer Militärkommandant, der an Sozialismus und Gleichheit für alle glaubte. Als der Krieg 1975 endete, wurde er der erste Präsident des Landes. Er baute neue Schulen und Krankenhäuser für die Armen und vereinte verschiedene Gruppen. Er half auch anderen afrikanischen Ländern im Freiheitskampf. 1986 starb er bei einem mysteriösen Flugzeugabsturz. Viele glauben, seine Feinde hätten den Absturz verursacht. Er bleibt ein geliebter Held in Mosambik und im gesamten Südlichen Afrika.",
    dict: { "führer":"lider", "mosambik":"mozambik", "unabhängigkeit":"bağımsızlık", "brachte":"getirdi", "leitete":"yönetti", "jahrelang":"yıllarca", "langen":"uzun", "schwierigen":"zor", "krieg":"savaş", "gegen":"karşı", "portugiesische":"portekiz", "armee":"ordu", "charismatischer":"karizmatik", "militärkommandant":"askeri komutan", "sozialismus":"sosyalizm", "gleichheit":"eşitlik", "glaubte":"inandı", "endete":"bitti", "erste":"ilk", "präsident":"başkan", "landes":"ülke", "baute":"inşa etti", "neue":"yeni", "schulen":"okullar", "krankenhäuser":"hastaneler", "armen":"fakirler", "vereinte":"birleştirdi", "verschiedene":"farklı", "gruppen":"gruplar", "half":"yardım etti", "anderen":"diğer", "afrikanischen":"afrikalı", "ländern":"ülkeler", "freiheitskampf":"özgürlük mücadelesi", "starb":"öldü", "mysteriösen":"gizemli", "flugzeugabsturz":"uçak kazası", "viele":"birçok", "glauben":"inanıyor", "feinde":"düşmanlar", "absturz":"kaza", "verursacht":"sebep oldu", "bleibt":"kalır", "geliebter":"sevilen", "held":"kahraman", "gesamten":"tüm", "südlichen":"güney" },
    questions: [ {q:"Brachte Samora Machel Mosambik die Unabhängigkeit?", a_de:"Ja", a_tr:"Evet"}, {q:"Leitete er einen Krieg gegen die französische Armee?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er 1975 der erste Präsident des Landes?", a_de:"Ja", a_tr:"Evet"}, {q:"Baute er neue Schulen und Krankenhäuser?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb er friedlich im hohen Alter in seinem Bett?", a_de:"Nein", a_tr:"Hayır"}, {q:"Glauben viele, seine Feinde hätten den Absturz verursacht?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist er ein geliebter Held im Südlichen Afrika?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["19_Biko.mp3"] = [{
    text: "19. Steve Biko. Steve Biko war ein brillanter junger Führer, der gegen Rassismus in Südafrika kämpfte. Er gründete die „Black Consciousness“-Bewegung, die schwarzen Menschen beibrachte, stolz auf sich selbst und ihre Geschichte zu sein. Er glaubte, der erste Schritt zur Freiheit sei, zu erkennen, dass man niemandem unterlegen ist. Die Regierung hatte große Angst vor seinen Ideen und verbot ihm, öffentlich zu sprechen. 1977 wurde er verhaftet und so brutal von der Polizei geschlagen, dass er starb. Er war nur 30 Jahre alt. Sein Tod machte die ganze Welt wütend auf die südafrikanische Regierung. Er wird für den berühmten Satz erinnert: „Black is beautiful.“",
    dict: { "brillanter":"parlak", "junger":"genç", "führer":"lider", "rassismus":"ırkçılık", "südafrika":"güney afrika", "kämpfte":"savaştı", "gründete":"kurdu", "bewegung":"hareket", "schwarzen":"siyah", "menschen":"insanlar", "beibrachte":"öğretti", "stolz":"gururlu", "selbst":"kendisi", "geschichte":"tarih", "glaubte":"inandı", "erste":"ilk", "schritt":"adım", "freiheit":"özgürlük", "sei":"olduğunu", "erkennen":"anlamak/fark etmek", "niemandem":"hiç kimseye", "unterlegen":"aşağı/düşük", "regierung":"hükümet", "große":"büyük", "angst":"korku", "ideen":"fikirler", "verbot":"yasakladı", "öffentlich":"açıkça/halka açık", "sprechen":"konuşmak", "verhaftet":"tutuklandı", "brutal":"acımasızca", "polizei":"polis", "geschlagen":"dövüldü", "starb":"öldü", "tod":"ölüm", "machte":"yaptı", "ganze":"tüm", "welt":"dünya", "wütend":"kızgın", "südafrikanische":"güney afrika", "erinnert":"hatırlanır", "berühmten":"ünlü", "satz":"cümle" },
    questions: [ {q:"Kämpfte Steve Biko gegen Rassismus in Südafrika?", a_de:"Ja", a_tr:"Evet"}, {q:"Lehrte seine Bewegung schwarze Menschen, stolz auf sich zu sein?", a_de:"Ja", a_tr:"Evet"}, {q:"Glaubte er, man müsse sich anderen unterlegen fühlen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Erlaubte die Regierung ihm, öffentlich zu sprechen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er im Gefängnis von der Polizei zu Tode geschlagen?", a_de:"Ja", a_tr:"Evet"}, {q:"Machte sein Tod die Welt wütend auf die Regierung?", a_de:"Ja", a_tr:"Evet"}, {q:"Wird er für den Satz „Black is beautiful“ erinnert?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["20_Sankara.mp3"] = [{
    text: "20. Thomas Sankara. Thomas Sankara war in den 1980er Jahren Präsident von Burkina Faso. Er war eine ganz andere Art von Führer, weil er ein sehr einfaches Leben führte und sich weigerte, reich zu sein, während sein Volk arm war. Er änderte den Namen seines Landes in Burkina Faso, was „Land der Unbestechlichen“ bedeutet. Er baute viele Schulen, pflanzte Millionen Bäume und setzte sich stark für Frauenrechte ein. Er wollte, dass sein Land unabhängig wird und nicht auf Geld aus anderen Nationen angewiesen ist. 1987 wurde er bei einem Putsch getötet, von Leuten, die seine radikalen Veränderungen nicht mochten. Er wird oft als „afrikanischer Che Guevara“ bezeichnet und ist ein Held für viele junge Afrikaner heute.",
    dict: { "präsident":"başkan", "ganz":"tamamen/çok", "andere":"başka/farklı", "art":"tür", "führer":"lider", "einfaches":"sade/basit", "leben":"hayat", "führte":"sürdürdü/yaşadı", "weigerte":"reddetti", "reich":"zengin", "während":"iken", "volk":"halk", "arm":"fakir", "änderte":"değiştirdi", "namen":"isim", "landes":"ülkesinin", "unbestechlichen":"dürüstler (rüşvet almayanlar)", "bedeutet":"anlamına gelir", "baute":"inşa etti", "schulen":"okullar", "pflanzte":"dikti", "bäume":"ağaçlar", "setzte":"koydu/kalkıştı (sich einsetzen: savunmak)", "stark":"güçlü", "frauenrechte":"kadın hakları", "unabhängig":"bağımsız", "geld":"para", "anderen":"diğer", "nationen":"uluslar", "angewiesen":"muhtaç/bağımlı", "putsch":"darbe", "getötet":"öldürüldü", "leuten":"insanlar", "radikalen":"radikal/köklü", "veränderungen":"değişiklikler", "mochten":"sevdiler (nicht mochten: sevmediler)", "oft":"sıklıkla", "afrikanischer":"afrikalı", "bezeichnet":"adlandırılır", "held":"kahraman", "junge":"genç" },
    questions: [ {q:"Führte Thomas Sankara ein sehr reiches und luxuriöses Leben?", a_de:"Nein", a_tr:"Hayır"}, {q:"Bedeutet Burkina Faso „Land der Unbestechlichen“?", a_de:"Ja", a_tr:"Evet"}, {q:"Pflanzte er Millionen Bäume und baute Schulen?", a_de:"Ja", a_tr:"Evet"}, {q:"Setzte er sich stark für Frauenrechte ein?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte er, dass sein Land von anderen Nationen abhängig bleibt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er bei einem Putsch getötet?", a_de:"Ja", a_tr:"Evet"}, {q:"Wird er oft als „afrikanischer Che Guevara“ bezeichnet?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["21_Arafat.mp3"] = [{
    text: "21. Yasser Arafat. Yasser Arafat war jahrzehntelang der bekannteste Führer des palästinensischen Volkes. Er verbrachte sein ganzes Leben im Kampf um ein Land für sein Volk. Er war Gründer der Fatah-Bewegung und Führer der PLO. Er war ein sehr komplizierter Mann, der sowohl Krieg als auch Frieden einsetzte, um seine Ziele zu erreichen. 1993 unterzeichnete er ein Friedensabkommen mit Israel und erhielt den Friedensnobelpreis. Er wurde der erste Präsident der Palästinensischen Autonomiebehörde. Er war ein Symbol des Kampfes seines Volkes und trug immer seinen berühmten „Kufiya“-Schal. Ob man mit ihm einverstanden war oder nicht – jeder wusste, dass er ein Mann war, der nie aufhörte, für Palästina zu kämpfen, bis zu seinem Tod.",
    dict: { "jahrzehntelang":"onyıllarca", "bekannteste":"en bilinen", "führer":"lider", "palästinensischen":"filistin", "volkes":"halkının", "verbrachte":"geçirdi", "ganzes":"tüm", "leben":"hayat", "kampf":"mücadele", "land":"ülke/toprak", "volk":"halk", "gründer":"kurucu", "bewegung":"hareket", "komplizierter":"karmaşık", "mann":"adam", "sowohl":"hem", "krieg":"savaş", "frieden":"barış", "einsetzte":"kullandı", "ziele":"hedefler", "erreichen":"ulaşmak", "unterzeichnete":"imzaladı", "friedensabkommen":"barış anlaşması", "israel":"israil", "erhielt":"aldı", "friedensnobelpreis":"nobel barış ödülü", "erste":"ilk", "präsident":"başkan", "autonomiebehörde":"özerk yönetim", "symbol":"sembol", "trug":"takardı/giyerdi", "berühmten":"ünlü", "schal":"atkı", "einverstanden":"aynı fikirde (einverstanden sein)", "wusste":"biliyordu", "nie":"asla", "aufhörte":"bıraktı/durdu (aufhören)", "kämpfen":"savaşmak", "bis":"kadar", "tod":"ölüm" },
    questions: [ {q:"War Yasser Arafat der bekannteste Führer der Palästinenser?", a_de:"Ja", a_tr:"Evet"}, {q:"Gründete er die Fatah-Bewegung?", a_de:"Ja", a_tr:"Evet"}, {q:"Setzte er nur friedliche Methoden ein, um seine Ziele zu erreichen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Unterzeichnete er 1993 ein Friedensabkommen mit Israel?", a_de:"Ja", a_tr:"Evet"}, {q:"Erhielt er den Friedensnobelpreis?", a_de:"Ja", a_tr:"Evet"}, {q:"Trug er immer seinen berühmten Kufiya-Schal?", a_de:"Ja", a_tr:"Evet"}, {q:"Hörte er jemals auf, für Palästina zu kämpfen?", a_de:"Nein", a_tr:"Hayır"} ]
}];
